version: '3'

services:
  chicago-vchat-db:
    container_name: chicago-vchat-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db-chicago:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
    networks:
      - mongonet

  vchat.chicago.dockerfully.com:
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: vchat.chicago
    image: mountain/nextcloud
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - nextcloud-chicago:/var/www/html
    environment:
      - VIRTUAL_HOST=vchat.chicago.dockerfully.com
      - LETSENCRYPT_HOST=vchat.chicago.dockerfully.com
      - VIRTUAL_PORT=8888
      - MYSQL_HOST=chicago-vchat-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
    depends_on:
      - chicago-vchat-db
    networks:
      - mongonet

volumes:
  db-chicago:
  nextcloud-chicago:
  html:

networks:
  mongonet:
    external: true
