version: '3'

services:
  rocks-vchat-db:
    container_name: rocks-vchat-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db-rocks:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
    networks:
      - mongonet

  vchat.frickin.rocks:
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: vchat.rocks
    image: rocks/nextcloud
    restart: always
    ports:
      - '7777:7777'
    volumes:
      - nextcloud-rocks:/var/www/html
    environment:
      - VIRTUAL_HOST=vchat.frickin.rocks
      - LETSENCRYPT_HOST=vchat.frickin.rocks
      - VIRTUAL_PORT=7777
      - MYSQL_HOST=rocks-vchat-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
    depends_on:
      - rocks-vchat-db
    networks:
      - mongonet

volumes:
  db-rocks:
  nextcloud-rocks:
  html:

networks:
  mongonet:
    external: true
