version: '3'

services:
  iowa-vchat-db:
    container_name: iowa-vchat-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db-iowa:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
    networks:
      - mongonet

  vchat.iowa.dockerfully.com:
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: vchat.iowa
    image: mountain/nextcloud
    restart: always
    ports:
      - '9999:9999'
    volumes:
      - nextcloud-iowa:/var/www/html
    environment:
      - VIRTUAL_HOST=vchat.iowa.dockerfully.com
      - LETSENCRYPT_HOST=vchat.iowa.dockerfully.com
      - VIRTUAL_PORT=9999
      - MYSQL_HOST=iowa-vchat-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
    depends_on:
      - iowa-vchat-db
    networks:
      - mongonet

volumes:
  db-iowa:
  nextcloud-iowa:
  html:

networks:
  mongonet:
    external: true
